# config/polls.yaml
postgres:
  database: postgres
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5

spring:
  application:
    name: rabbitmq-producer-basic
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest